### ISSUE TITLE
DRB5*01:01:01  not listed under alignments directory.

### ISSUE THREAD

**Issue by heewookl** [ANHIG/IMGTHLA#106]
I find alignment flat file format useful as it already has intron exon boundaries embedded. 

DRB5*01:01:01 allele is not listed under "alignments" directory whereas it is listed under "msf" directory.

Is this because there is only one full-length allele of DRB5? But in the README file, gen.txt description says: 

"Please note for alleles that do not possess genomic sequences, there will be no entry in the file"

So for DRB5 even with one allele, there should be DRB5_gen.txt file containing the DRB5*01:01:01 allele.

Under msf directory, it is listed under DRB5_gen.msf but there is no corresponding alignment file DRB5_gen.txt under alignments directory.

**Comment by ANHIG** [comment]
Many thanks for raising this, we are currently reviewing the contents of the next release and will look at this issue.


On 20 Jun 2017, at 07:25, heewookl <notifications@github.com<mailto:notifications@github.com>> wrote:


I find alignment flat file format useful as it already has intron exon boundaries embedded.

DRB5*01:01:01 allele is not listed under "alignments" directory whereas it is listed under "msf" directory.

Is this because there is only one full-length allele of DRB5? But in the README file, gen.txt description says:

"Please note for alleles that do not possess genomic sequences, there will be no entry in the file"

So for DRB5 even with one allele, there should be DRB5_gen.txt file containing the DRB5*01:01:01 allele.

Under msf directory, it is listed under DRB5_gen.msf but there is no corresponding alignment file DRB5_gen.txt under alignments directory.

**Comment by ANHIG** [comment]
The README has been updated to reflect that for alleles that do not possess genomic sequences there will be no entry in the file, or where there is only a single genomic sequence at the locus, a file will not be produced.
