### ISSUE TITLE
HLA-DMB*01:02 - Invalid join

### ISSUE THREAD

**Issue by mhalagan** [ANHIG/IMGTHLA#118]
**HLA00490 - 3.30.0**

The `join(<1..284)` is invalid because a join should have at least two parts.  

```
DR   EMBL; Z24750; Z24750.1.
XX
FH   Key             Location/Qualifiers
FH
FT   source          1..284
FT                   /organism="Homo sapiens"
FT                   /mol_type="genomic DNA"
FT                   /db_xref="taxon:9606"
FT                   /ethnic="Caucasoid"
FT                   /cell_line="YAR"
FT   CDS             join(<1..284)
FT                   /codon_start=1
FT                   /partial
FT                   /gene="HLA-DMB"
FT                   /allele="HLA-DMB*01:02"
FT                   /product="MHC Class II HLA-DMB*01:02 sequence"
FT                   /translation="PPSVQVAKTTPFNTREPVMLACYVWGFYPAEVTITWRKNGKLVMP
FT                   HSSEHKTAQPNGDWTYQTLSHLALTPSYGDTYTCVVEHIGAPEPILRDW"
FT   exon            1..284
FT                   /number="3"
FT                   /partial
SQ   Sequence 284 BP; 67 A; 83 C; 74 G; 60 T; 0 other;
     ggccaccatc tgtgcaagta gccaaaacca ctccttttaa cacgagggag cctgtgatgc        60
     tggcctgcta tgtgtggggc ttctatccag cagaagtgac tatcacgtgg aggaagaacg       120
     ggaagcttgt catgcctcac agcagtgagc acaagactgc ccagcccaat ggagactgga       180
     cataccagac cctctcccat ttagccttaa ccccctctta cggggacact tacacctgtg       240
     tggtagagca cattggggct cctgagccca tccttcggga ctgg                        284
//
```

Having this error in the `hla.dat` file causes bio parsers to fail.

**Comment by ANHIG** [comment]
Thank you for reporting this issue with certain bio parsers. We will look into applying a patch to the currently released version.


On 9 Nov 2017, at 15:50, Michael Halagan <notifications@github.com<mailto:notifications@github.com>> wrote:


HLA00490 - 3.30.0

The join(<1..284) is invalid because a join should have at least two parts.

DR   EMBL; Z24750; Z24750.1.
XX
FH   Key             Location/Qualifiers
FH
FT   source          1..284
FT                   /organism="Homo sapiens"
FT                   /mol_type="genomic DNA"
FT                   /db_xref="taxon:9606"
FT                   /ethnic="Caucasoid"
FT                   /cell_line="YAR"
FT   CDS             join(<1..284)
FT                   /codon_start=1
FT                   /partial
FT                   /gene="HLA-DMB"
FT                   /allele="HLA-DMB*01:02"
FT                   /product="MHC Class II HLA-DMB*01:02 sequence"
FT                   /translation="PPSVQVAKTTPFNTREPVMLACYVWGFYPAEVTITWRKNGKLVMP
FT                   HSSEHKTAQPNGDWTYQTLSHLALTPSYGDTYTCVVEHIGAPEPILRDW"
FT   exon            1..284
FT                   /number="3"
FT                   /partial
SQ   Sequence 284 BP; 67 A; 83 C; 74 G; 60 T; 0 other;
     ggccaccatc tgtgcaagta gccaaaacca ctccttttaa cacgagggag cctgtgatgc        60
     tggcctgcta tgtgtggggc ttctatccag cagaagtgac tatcacgtgg aggaagaacg       120
     ggaagcttgt catgcctcac agcagtgagc acaagactgc ccagcccaat ggagactgga       180
     cataccagac cctctcccat ttagccttaa ccccctctta cggggacact tacacctgtg       240
     tggtagagca cattggggct cctgagccca tccttcggga ctgg                        284
//


Having this error in the hla.dat file causes bio parsers to fail.

**Comment by ANHIG** [comment]
The CDS line of the hla.dat file has been updated, in response to
reported parser errors. The ‘<‘ has been removed from all entries and
the join condition is only used when at least two blocks of coordinates
are listed.
