### ISSUE TITLE
hla.dat file not downloading properly

### ISSUE THREAD

**Issue by cfrangus** [ANHIG/IMGTHLA#173]
I tried downloading the IMGT zip but the hla.dat file does not contain the alleles as expected.  Instead it contains the following:
version https://git-lfs.github.com/spec/v1
oid sha256:1b26676d2366ba8768122a973aa0add3641671430a52a431e03b6700b8459ff1
size 113160320

**Comment by cfrangus** [comment]
This site has the file file: ftp://ftp.ebi.ac.uk/pub/databases/imgt/mhc/hla/

**Comment by zimoun** [comment]
Basically, you need to install the program `git-lfs` from:
https://git-lfs.github.com/
Then, `git lfs pull` will populate the folder with the expected `hla.dat` moderately big (108M) and other.

Hope that helps.

**Comment by jrob119** [comment]
Due to the increasing file sizes for the hla.dat and some of the compressed zip files, the repository now requires the Git LFS tools (https://git-lfs.github.com) which handles file over 100MB. Please use these when cloning to ensure the larger files are downloaded correctly. If Git LFS is not used then large files will contain pointers to the Git LFS location rather than the data required.
