### ISSUE TITLE
Please implement holistic versioning

### ISSUE THREAD

**Issue by mmaiers-nmdp** [ANHIG/IMGTHLA#235]
When making minor releases (e.g. 3.41.1, 3.41.2) the version should be updated across the entire IMGT/HLADB system.
Currently only the updated files get the version updates which means some files in the "LATEST" repo have different versions from other files. 

Ideally there should a file (current_version.txt) that indicates the version of the entire IMGT/HLADB so that systems that consume the data don't have to parse HMTL pages (that may not be in sync with the repo).

**Comment by jrob119** [comment]
Many thanks for raising this issue, we are constantly looking at how best to report the versioning of the release and in particular for the minor versioning, where we are keen to highlight the important changes to the data.  

Updating all files with the latest release number would mean consistency across all files, but also means a lot of files with no underlying changes need updating and are flagged as changed because a single line with the version has been updated. This one of the reasons for not using this approach at the current time.

The use of a single file indicating the current version, could be a way forward to aid with this.

**Comment by pbashyal-nmdp** [comment]
I noticed `release_version.txt` file added to `Latest` and `3420` version/branch. Can we expect this to be added to new versions going forward ?

**Comment by jrob119** [comment]
Yes, we intend to continue to provide this file moving forward.

**Comment by pbashyal-nmdp** [comment]
Thank you! That'll be very helpful.
