### ISSUE TITLE
Exon 2 annotation on HLA-A*01:01:01:02N

### ISSUE THREAD

**Issue by RomuloVianna** [ANHIG/IMGTHLA#300]
This issue is about the exon 2 annotation on the HLA-A*01:01:01:02N allele (HLA02169).

Since for this allele there is a deletion that occurs in a region that is STOP codon for HLA-A*01:01:01 alleles (g478-481delGTGA), the exon 2 should not stop where it is annotated at the hla.xml file but continue for more 86 amino acids (GDPGPGRRSRPLIPHGRARSPTVSGSEIHPEAAGLRDPCPGRGPGAFTRFHFQFRPKIPPGWSGRGGARGTGLTAGSGPGSHTIQ) until the new STOP codon. Until the latest database (v3.47), this problem persists and should be resolved.

**Comment by jrob119** [comment]
Many thanks for raising this, one of the team will look into this allele and the protein translation provided.

**Comment by jrob119** [comment]
Apologies for the delay in resolving this, the sequence originates from a single submission, and the CDS may be impacted by a 4 bp deletion in intron 2, this makes it harder to predict the CDS and resulting protein from the end of the exon 2 onwards. We continue to review and follow up with the original submission to understand why the protein sequence presented is used, and not alternative translations due to the deletion mentioned earlier.
