### ISSUE TITLE
3480 Allelelist file not in Latest/allelelist/ directory

### ISSUE THREAD

**Issue by pbashyal-nmdp** [ANHIG/IMGTHLA#302]
The allelelist file until 3470 has been `Latest/allelelist/Allelelist.{version}.txt` path but 3480 is not in that directory: https://github.com/ANHIG/IMGTHLA/tree/Latest/allelelist but it is available in [3480 branch](https://github.com/ANHIG/IMGTHLA/tree/3480/allelelist). Is this an oversight or is it a new change ?

**Comment by dominicbarkerAN** [comment]
Hello, thanks for raising this issue. The 3.48.0 release had, on Thursday, been published to the 3480 branch of the git repository however due to the bank holidays in the UK was not pulled into Latest until this morning. I apologise for the inconvenience but you should now be able to access all of the 3.48.0 files in the Latest branch.

**Comment by pbashyal-nmdp** [comment]
Thank you!
