### ISSUE TITLE
nucRefAl: DRB1*01:01:01:01	genRefAl: DRB5*01:01:01 refGeneName on nuc and gen are NOT same onn 3.48.0

### ISSUE THREAD

**Issue by mainguyenanhvu** [ANHIG/IMGTHLA#307]
I try to build a custom database for https://github.com/Kingsford-Group/kourami by using IMGTHLA 3.48.0 via the command:
```
./formatIMGT.sh -i ../../IMGTHLA/alignments
```
Then, it returned error: 
```
nucRefAl:	DRB1*01:01:01:01	genRefAl:	DRB3*01:01:02:01
	refGeneName on nuc and gen are NOT same
	SWAPPING refGenes on nuc and gen
	Wrting to : kourami/scripts/../custom_db/3.48.0/DRB3_gen.txt
	Wrting to : kourami/scripts/../custom_db/3.48.0/DRB3_nuc.txt
>>>>>>>>>  Processing	[DRB4]  <<<<<<<<<<
nucRefAl:	DRB1*01:01:01:01	genRefAl:	DRB4*01:01:01:01
	refGeneName on nuc and gen are NOT same
	SWAPPING refGenes on nuc and gen
	Wrting to : kourami/scripts/../custom_db/3.48.0/DRB4_gen.txt
	Wrting to : kourami/scripts/../custom_db/3.48.0/DRB4_nuc.txt
>>>>>>>>>  Processing	[DRB5]  <<<<<<<<<<
nucRefAl:	DRB1*01:01:01:01	genRefAl:	DRB5*01:01:01
	refGeneName on nuc and gen are NOT same
Reference sequence entry [DRB5*01:01:01] is NOT found in nuc alignments.
Check the alignment files.
```

please check it. Thank you.

**Comment by dominicbarkerAN** [comment]
Hello,

Kourami is not a piece of software maintained by us so we cannot comment on it's inner workings

However from looking at the error message you have posted I can say that in the case of DRB3, DRB4 and DRB5 we do indeed use a different reference for the *_nuc.txt and *_gen.txt files. This is because these, as well as DRB1, are very closely related genes with similar coding sequences. We have always used a single reference covering all of these genes at the CDS for ease of comparison. However the intronic sequences are more distinct so we use an alternative reference unique to each locus.

I think the issue causing the failure is that DRB5*01:01:01 is listed as the reference for DRB5. However this is out of date. The DRB5*01:01:01 allele designation was extended to DRB5*01:01:01:01 in release 3.33.0, which was in July 2018.

You will need to get into contact with the developers of Kourami about correcting this.
