### ISSUE TITLE
Files with different checksum in release 3.49.0

### ISSUE THREAD

**Issue by gariem** [ANHIG/IMGTHLA#321]
The following files have different checksums, after downloading the .tar file (md5checksum.txt / calculated):

hla.dat (6aee718a919b23b0dcbdaeef0b536192 / 2a52515be430b21a9eb6195abdffcd38)
Allelelist_history.txt (45046a10098ac0f108d0c4dcf6d78389 / 512c0d85101994f92e01b54863e6e26b)

Can you confirm the files are correct?

The files in the FTP server (ftp://ftp.ebi.ac.uk/pub/databases/ipd/imgt/hla/) don't present the problem, but it's a different version (3.50.0).

**Comment by gariem** [comment]
Tagging @dominicbarkerAN  @jrob119

**Comment by dominicbarkerAN** [comment]
Hi Emilio Garcia,

Thank you for bringing this issue to our attention. Clearly the hla.dat and Allelelist_history.txt files were updated after the initial release and the md5 checksums were not updated accordinly. I have updated the md5 checksums on the 3490 branch. 

To confirm the Alleleist_history.txt has changed from
6aee718a919b23b0dcbdaeef0b536192 -> 2a52515be430b21a9eb6195abdffcd38

I believe this resolves your issue with the Allelelist_history.txt file, and the ordering is incorrect in your initial issue, please correct me if I am wrong.

The hla.dat file on the other hand has changed from
45046a10098ac0f108d0c4dcf6d78389 -> 13a7b5bab7687d601b321cb34c8e92f8

This differs from the calculated md5 checksum you suggested. This is due to the hla.dat file being stored using git-lfs due to it's large file size. We are looking into enabling files stored using git-lfs to be correctly downloaded in .tar files.

In the meantime you can access this file with git-lfs installed by cloning the repository.

**Comment by gariem** [comment]
Thank you very much!
