### ISSUE TITLE
B*15:150 allele not present in hla_gen.fasta or B_gen.fasta

### ISSUE THREAD

**Issue by huzuner** [ANHIG/IMGTHLA#326]
Hi,

The allele B*15:150 is unfortunately not present neither in hla_gen.fasta nor in B_gen.fasta in IPD-IMGT/HLA 3.32, even though it is present in hla.xml and hla_nom_g.txt of the same version.
I hope that it can be updated soon.

Best regards,
huzuner

**Comment by dominicbarkerAN** [comment]
Hello,

Having reviewed the associated files in 3.32.0 I can see that B*15:150 at that time - it has since been extended - only included exons 2, 3 and 4. In order to be included in the B_gen.fasta the entire sequences for an allele from the start codon to the stop codon including all intervening exons and introns must be included.

The sequence would be correctly included in the hla.xml as partial sequences can be included here, and the hla_nom_g.txt file which is based off of the sequences of exon 2 and 3.

The release you are reviewing is also now almost five years old and we recommend using more recent versions of the database - particularly those in the last two years - for which we can provide faster support.
