### ISSUE TITLE
Why is B*55:134 in the B*56:01:01G and B*56:01P groups? IPD-IMGT/HLA Release 3.51.0

### ISSUE THREAD

**Issue by saulievue** [ANHIG/IMGTHLA#330]
Hi all,

We checked the hla_nom_g.txt and hla_nom_p.txt files and are wondering why B*55:134 is in the B*56:01:01G and B*56:01P groups? Could you please verify and confirm if this is correct?

Thanks,
Saulie

**Comment by dominicbarkerAN** [comment]
Hi Saulie,

Thank you for bringing this issue to our attention. I can confirm that the sequence of B*55:134 is correct and should be placed in the B*56:01:01G and B*56:01P groups. However we agree that the inclusion of B*55:134 within B*55 allele group is inappropriate and that this allele would be better named as a B*56 allele. This allele will be renamed in due course and that change will be reflected in the appropriate files once made.

Thank you again for bringing this issue to our attention so that it can be corrected.
