### ISSUE TITLE
HLA-DPB1*1332N exon border change

### ISSUE THREAD

**Issue by marcellmarton** [ANHIG/IMGTHLA#343]
In 3.52.0 database the exon3 border of HLA-DPB1*1332N is 365..645, in the 3.53.0 version it is 365..644 however it is not mentioned in the version report. Is the change correct and intended or is it a mistake of some sort?
Thank you!

**Comment by michaelcooperAN** [comment]
The sequence for HLA-DPB1*1332N has not changed between these two releases, which is why it was not included in the version report. The position of indels, however, is subject to being changed, and the indel in the exon 3 boundary has been changed to better represent how the sequence should look.
I hope this helps!
