### ISSUE TITLE
An unexpected change in hla.xml format

### ISSUE THREAD

**Issue by mallen2** [ANHIG/IMGTHLA#349]
Hi guys,

I hope you are well. 

I see that the hla.xml file has been reformatted, again. Was this change announced somewhere? If so can you point me to the place where we can get these announcements, so that we can prepare prior to the new allele releases?  

Unexpected change like this add delays to our adoption of the newest allele version. This has consequences for the HLA community in general. NMDP provides the multiple allele code creation service to the HLA community. If we are not using the latest release, no one  can make allele codes with the new alleles. 

For this release in particular is it possible to generate an hla.xml file the old way? 

Thanks!
Marney

**New format**
<?xml version="1.0" encoding="ISO-8859-1" ?>
<release version="3.54.0" date="2023-10-12" xmlns="http://hla.alleles.org/xml" xmlns:xs="http://www.w3.org/2001/XMLSchema" xs:noNamespaceSchemaLocation="http://hla.alleles.org/xml/hla.xsd">
  <alleles>
    <allele id="HLA00001" name="HLA-A*01:01:01:01" dateassigned="1989-08-01">

**Previous format**
<?xml version="1.0" encoding="ISO-8859-1" ?>
<alleles xmlns="http://hla.alleles.org/xml" xmlns:xs="http://www.w3.org/2001/XMLSchema" xs:noNamespaceSchemaLocation="http://hla.alleles.org/xml/hla.xsd">
  <allele id="HLA00001" name="HLA-A*01:01:01:01" dateassigned="1989-08-01">

**Comment by bmschoene** [comment]
I second the need to **please please** announce any intended changes to the format of your files beforehand - preferrably with 3 months warning. Especially for the hla.xml and hla.dat and their corresponding files in IPD-KIR. That allows people using those files to adjust their software in advance.

I suppose opening an announcement issue here on GitHub yourself would serve this purpose well, as the people who depend on these files regularly are probably all subscribed here.

In instances where such a warning cannot be done for whatever reason, please provide the files in both the new and the old format for the first release introducing the format change, which will then work as a deprecation warning. (You could use a file name suffix to separate them.)

In both cases, **please announce format changes very visibly in the release notes**! Don't just note them down somewhere in the Readme. This is what Release notes are _for_!

**Comment by dominicbarkerAN** [comment]
Hello,

Thank you for bringing this issue to our attention. The hla.xml file included in the initial 3.54.0 release of the database is incorrect and has now been updated on the 3.54.0 and Latest branch. We apologise for any inconvenience this has caused. 

We continue to review the best way to present the information from the database across our different file formats however we are cautious about making significant changes or frequent changes. The hla.xml file included in the initial release of 3.54.0 is an development version and not intended for public use, it's inclusion in 3.54.0 is an error. I apologise the confusion.

In future we may change the format of this file however we will not do so until we have agreed upon a format, with consultation from users, that will be consistent from then on. At that time an announcment will be made of the intended changes and both old and new formats will be available for that release.

Thank you again for bringing this issue to our attention so that we can resolve it as soon as possible. We will contact key users directly to provide them with a development version of the hla.xml we are intending for future use.

**Comment by mallen2** [comment]
Thank you for attending to this quickly!

Marney Milsten
Product Owner, Genomic Services
500 N 5th St, Minneapolis, MN 55401-1206.
Phone: (763) 406-8305 Email: ***@***.***

***@***.***
***@***.***
Be the one to save a life. Be The Match. Join now<http://marrow.org/JOIN/Join_Now/join_now.html>.
